name: main

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  auto-merge-helper:
    runs-on: ubuntu-latest
    steps:
      - run: curl -s https://api.github.com/repos/tokizuoh/auto-merge-helper/releases/latest | jq -r '.assets[0].browser_download_url' | xargs curl -LJO
      - run: chmod +x ./sample
      - run: sleep 60
      - run: ./sample
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
